_BASE_: "Base-OneNet.yaml"
MODEL:
  WEIGHTS: "models/torchvision-R-18.pkl"
  BACKBONE:
      FREEZE_AT: 0
  RESNETS:
    NORM: "BN"
    DEPTH: 18
    STRIDE_IN_1X1: False
    RES2_OUT_CHANNELS: 64
  OneNet:
    DCN: True
    NUM_CLASSES: 10
    DECONV_CHANNEL: (512, 256, 128, 64)
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST:  ("coco_2017_val",)
SOLVER:
  IMS_PER_BATCH: 32
  STEPS: (20000, 25000)
  MAX_ITER: 30000
INPUT:
  CROP:
    ENABLED: True
  FORMAT: "RGB"
OUTPUT_DIR: 'output_onenet_r18dcn'
